[theme]
# On force le thème sombre de base (c'est la formule magique !)
base = "dark"

# On garde notre vert "Nature" pour les boutons et les barres de progression
primaryColor = "#4CAF50"

# Couleurs de fond spécifiques au mode sombre
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"

# Texte en blanc/gris très clair pour un contraste parfait sans éblouir
textColor = "#FAFAFA"

# On garde une police moderne et claire
font = "sans serif"