[theme]
# La couleur principale (utilisée pour les boutons, les barres de progression, etc.)
# Ici, un beau vert "Nature"
primaryColor = "#4CAF50"

# La couleur de fond principal de l'application (blanc pur)
backgroundColor = "#FFFFFF"

# La couleur de fond secondaire (utilisée pour les encadrés et la barre latérale)
# Un gris très très clair, presque bleuté, pour un effet "médical/propre"
secondaryBackgroundColor = "#F0F2F6"

# La couleur du texte principal (Gris anthracite pour une lecture douce sans fatiguer les yeux)
textColor = "#262730"

# La police d'écriture (options: "sans serif", "serif", "monospace")
font = "sans serif"